name = "aura-voice"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "aura-voice"

[vars]
LIVEKIT_API_KEY = ""
LIVEKIT_API_SECRET = ""
R2_PUBLIC_URL = ""
R2_ACCESS_KEY_ID = ""
R2_BUCKET_NAME = "aura-voice"
LIVEKIT_URL = ""
R2_ACCOUNT_ID = ""
R2_SECRET_ACCESS_KEY = ""
